version: '3.9'
services:
  npm:
    image: node-permission
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: npm
    tty: true

  test:
    image: node-permission
    container_name: test
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    entrypoint: npm test