version: '3.9'
services:
  npm:
    image: 'node:16'
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: npm
    tty: true

  test:
    image: 'node:16'
    container_name: test
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: npm test